export const EXCEL_REHABS = [
  {
    "id": "REH0001",
    "debtorId": "NPL0009",
    "debtorName": "정웅선",
    "brand": "B",
    "court": "청주지법",
    "caseNumber": "2025개회34142",
    "type": "회생",
    "creditorNumber": "18",
    "planApproved": false,
    "dismissed": false,
    "debtAmount": 8606924,
    "approvedAmount": 2889494,
    "currentRound": "33회차",
    "monthlyPayment": 33165,
    "repaymentNote": "26.03.27 채권자목록및변제계획안 송달 完",
    "overdueStatus": ""
  },
  {
    "id": "REH0002",
    "debtorId": "NPL0010",
    "debtorName": "김용진95",
    "brand": "B",
    "court": "수원회생법원",
    "caseNumber": "2023개회141973",
    "type": "회생",
    "creditorNumber": "",
    "planApproved": false,
    "dismissed": true,
    "debtAmount": 19808607,
    "approvedAmount": 5218570,
    "currentRound": "",
    "monthlyPayment": 121994,
    "repaymentNote": "26.01.08 폐지",
    "overdueStatus": ""
  },
  {
    "id": "REH0003",
    "debtorId": "NPL0010",
    "debtorName": "김용진95",
    "brand": "B",
    "court": "수원회생법원",
    "caseNumber": "2026개회102880",
    "type": "회생",
    "creditorNumber": "18",
    "planApproved": false,
    "dismissed": false,
    "debtAmount": 0,
    "approvedAmount": 0,
    "currentRound": "",
    "monthlyPayment": 0,
    "repaymentNote": "추심금지결정문 수령",
    "overdueStatus": ""
  },
  {
    "id": "REH0004",
    "debtorId": null,
    "debtorName": "홍슬기",
    "brand": "B",
    "court": "수원회생법원",
    "caseNumber": "2024하단288",
    "type": "파산/면책",
    "creditorNumber": "",
    "planApproved": false,
    "dismissed": false,
    "debtAmount": 0,
    "approvedAmount": 0,
    "currentRound": "",
    "monthlyPayment": 0,
    "repaymentNote": "",
    "overdueStatus": ""
  },
  {
    "id": "REH0005",
    "debtorId": "NPL0021",
    "debtorName": "이용석",
    "brand": "B",
    "court": "인천지법",
    "caseNumber": "2024개회148172",
    "type": "회생",
    "creditorNumber": "13",
    "planApproved": true,
    "dismissed": false,
    "debtAmount": 17212613,
    "approvedAmount": 7025391,
    "currentRound": "21회차",
    "monthlyPayment": 344983,
    "repaymentNote": "26.03.05 기준 18회차/6.89회 미납",
    "overdueStatus": "미납"
  },
  {
    "id": "REH0006",
    "debtorId": "NPL0034",
    "debtorName": "조용석",
    "brand": "B",
    "court": "대전지법",
    "caseNumber": "2023개회102078",
    "type": "회생",
    "creditorNumber": "",
    "planApproved": false,
    "dismissed": true,
    "debtAmount": 74603182,
    "approvedAmount": 63745449,
    "currentRound": "6회차",
    "monthlyPayment": 1836759,
    "repaymentNote": "변제계획승인 없이 폐지(25.08.11)",
    "overdueStatus": ""
  },
  {
    "id": "REH0007",
    "debtorId": "NPL0038",
    "debtorName": "박인규",
    "brand": "B",
    "court": "수원회생법원",
    "caseNumber": "2024개회155603",
    "type": "회생",
    "creditorNumber": "11",
    "planApproved": false,
    "dismissed": false,
    "debtAmount": 5557672,
    "approvedAmount": 1829284,
    "currentRound": "5회차",
    "monthlyPayment": 54317,
    "repaymentNote": "26.02.11 6회 미납",
    "overdueStatus": "미납"
  },
  {
    "id": "REH0008",
    "debtorId": "NPL0042",
    "debtorName": "김상훈",
    "brand": "B",
    "court": "울산지법",
    "caseNumber": "2023개회64413",
    "type": "회생",
    "creditorNumber": "13",
    "planApproved": true,
    "dismissed": false,
    "debtAmount": 13630885,
    "approvedAmount": 5284152,
    "currentRound": "1~36회차",
    "monthlyPayment": 146783,
    "repaymentNote": "260227 기준 미납 1회/ 26회차/ 3회분 금원 딜레이(440349원) 및 입금확인 必",
    "overdueStatus": "미납"
  },
  {
    "id": "REH0009",
    "debtorId": null,
    "debtorName": "정성훈",
    "brand": "B",
    "court": "서울회생법원",
    "caseNumber": "2025개회37743",
    "type": "회생",
    "creditorNumber": "12",
    "planApproved": true,
    "dismissed": false,
    "debtAmount": 34481995,
    "approvedAmount": 10181575,
    "currentRound": "23회차",
    "monthlyPayment": 28708,
    "repaymentNote": "26.01.22 미납 3.23회",
    "overdueStatus": "미납"
  },
  {
    "id": "REH0010",
    "debtorId": "NPL0049",
    "debtorName": "서현영",
    "brand": "B",
    "court": "의정부지법",
    "caseNumber": "2024개회220884",
    "type": "회생",
    "creditorNumber": "10",
    "planApproved": true,
    "dismissed": false,
    "debtAmount": 10554113,
    "approvedAmount": 2784982,
    "currentRound": "19회차",
    "monthlyPayment": 13579,
    "repaymentNote": "26.03.20 미납 10회",
    "overdueStatus": "미납"
  },
  {
    "id": "REH0011",
    "debtorId": "NPL0062",
    "debtorName": "이준혁",
    "brand": "B",
    "court": "수원회생법원",
    "caseNumber": "2024개회102913",
    "type": "회생",
    "creditorNumber": "18-1",
    "planApproved": true,
    "dismissed": false,
    "debtAmount": 12884090,
    "approvedAmount": 2210610,
    "currentRound": "4회차",
    "monthlyPayment": 11826,
    "repaymentNote": "",
    "overdueStatus": ""
  },
  {
    "id": "REH0012",
    "debtorId": null,
    "debtorName": "정진원1",
    "brand": "B",
    "court": "서울회생법원",
    "caseNumber": "2022하단105315",
    "type": "파산/면책",
    "creditorNumber": "",
    "planApproved": false,
    "dismissed": false,
    "debtAmount": 0,
    "approvedAmount": 0,
    "currentRound": "",
    "monthlyPayment": 0,
    "repaymentNote": "",
    "overdueStatus": ""
  },
  {
    "id": "REH0013",
    "debtorId": "NPL0086",
    "debtorName": "전영재",
    "brand": "B",
    "court": "서울회생법원",
    "caseNumber": "2022개회1153981",
    "type": "회생",
    "creditorNumber": "8",
    "planApproved": true,
    "dismissed": false,
    "debtAmount": 19026965,
    "approvedAmount": 5127955,
    "currentRound": "6회차",
    "monthlyPayment": 37434,
    "repaymentNote": "",
    "overdueStatus": ""
  },
  {
    "id": "REH0014",
    "debtorId": "NPL0088",
    "debtorName": "전승구",
    "brand": "B",
    "court": "서울회생법원",
    "caseNumber": "2024개회19952",
    "type": "회생",
    "creditorNumber": "16",
    "planApproved": true,
    "dismissed": false,
    "debtAmount": 39529496,
    "approvedAmount": 5099716,
    "currentRound": "55회차",
    "monthlyPayment": 203546,
    "repaymentNote": "26.01.22 미납 3.98회",
    "overdueStatus": "미납"
  },
  {
    "id": "REH0015",
    "debtorId": "NPL0090",
    "debtorName": "최은호",
    "brand": "B",
    "court": "서울회생법원",
    "caseNumber": "2023개회1135140",
    "type": "회생",
    "creditorNumber": "",
    "planApproved": false,
    "dismissed": true,
    "debtAmount": 22722817,
    "approvedAmount": 1855184,
    "currentRound": "20회차",
    "monthlyPayment": 69696,
    "repaymentNote": "2024.10.18 폐지",
    "overdueStatus": ""
  },
  {
    "id": "REH0016",
    "debtorId": null,
    "debtorName": "박희석",
    "brand": "D",
    "court": "울산지법",
    "caseNumber": "2025개회12258",
    "type": "회생",
    "creditorNumber": "22",
    "planApproved": false,
    "dismissed": false,
    "debtAmount": 16331928,
    "approvedAmount": 2900692,
    "currentRound": "39회차",
    "monthlyPayment": 115504,
    "repaymentNote": "채권자집회기일:26.05.29",
    "overdueStatus": ""
  },
  {
    "id": "REH0017",
    "debtorId": null,
    "debtorName": "이동주(박희석 연대보증인)",
    "brand": "D",
    "court": "부산지법",
    "caseNumber": "2025개회119120",
    "type": "회생",
    "creditorNumber": "",
    "planApproved": false,
    "dismissed": false,
    "debtAmount": 0,
    "approvedAmount": 0,
    "currentRound": "",
    "monthlyPayment": 0,
    "repaymentNote": "",
    "overdueStatus": ""
  },
  {
    "id": "REH0018",
    "debtorId": "NPL0095",
    "debtorName": "이승기",
    "brand": "B",
    "court": "서울회생법원",
    "caseNumber": "2023개회15410",
    "type": "회생",
    "creditorNumber": "",
    "planApproved": false,
    "dismissed": true,
    "debtAmount": 36798000,
    "approvedAmount": 950309,
    "currentRound": "57 회차",
    "monthlyPayment": 8486,
    "repaymentNote": "2025.08.21 폐지",
    "overdueStatus": ""
  },
  {
    "id": "REH0019",
    "debtorId": "NPL0095",
    "debtorName": "이승기",
    "brand": "B",
    "court": "인천지방법원",
    "caseNumber": "2025개회10505",
    "type": "회생",
    "creditorNumber": "",
    "planApproved": false,
    "dismissed": true,
    "debtAmount": 0,
    "approvedAmount": 0,
    "currentRound": "",
    "monthlyPayment": 0,
    "repaymentNote": "2026.03.03 폐지공고(이의 확인)",
    "overdueStatus": ""
  },
  {
    "id": "REH0020",
    "debtorId": "NPL0096",
    "debtorName": "문준호",
    "brand": "B",
    "court": "부산회생법원",
    "caseNumber": "2024개회197874",
    "type": "회생",
    "creditorNumber": "16-1",
    "planApproved": true,
    "dismissed": false,
    "debtAmount": 13055157,
    "approvedAmount": 3585201,
    "currentRound": "2회차",
    "monthlyPayment": 87281,
    "repaymentNote": "",
    "overdueStatus": ""
  },
  {
    "id": "REH0021",
    "debtorId": "NPL0111",
    "debtorName": "김승환",
    "brand": "B",
    "court": "서울회생법원",
    "caseNumber": "2024하면103576",
    "type": "파산/면책",
    "creditorNumber": "",
    "planApproved": false,
    "dismissed": false,
    "debtAmount": 0,
    "approvedAmount": 0,
    "currentRound": "",
    "monthlyPayment": 0,
    "repaymentNote": "",
    "overdueStatus": ""
  },
  {
    "id": "REH0022",
    "debtorId": "NPL0124",
    "debtorName": "금창권",
    "brand": "B",
    "court": "인천지법",
    "caseNumber": "2024개회164570",
    "type": "회생",
    "creditorNumber": "9-1",
    "planApproved": true,
    "dismissed": false,
    "debtAmount": 24111837,
    "approvedAmount": 3945259,
    "currentRound": "18 회차",
    "monthlyPayment": 99769,
    "repaymentNote": "26.03.05 미납 7회/ 변제현황 조회 X",
    "overdueStatus": "미납"
  },
  {
    "id": "REH0023",
    "debtorId": "NPL0134",
    "debtorName": "백요한",
    "brand": "B",
    "court": "대전지법",
    "caseNumber": "2024개회68397",
    "type": "회생",
    "creditorNumber": "19",
    "planApproved": true,
    "dismissed": false,
    "debtAmount": 11839749,
    "approvedAmount": 1584868,
    "currentRound": "22회차",
    "monthlyPayment": 6386,
    "repaymentNote": "26.03.05 기준 22회차 / 미납5.32회",
    "overdueStatus": "미납"
  },
  {
    "id": "REH0024",
    "debtorId": "NPL0144",
    "debtorName": "윤용준",
    "brand": "B",
    "court": "",
    "caseNumber": "2024개회1149955",
    "type": "회생",
    "creditorNumber": "16-1",
    "planApproved": false,
    "dismissed": false,
    "debtAmount": 13905545,
    "approvedAmount": 4366709,
    "currentRound": "2회차",
    "monthlyPayment": 47655,
    "repaymentNote": "완료",
    "overdueStatus": ""
  },
  {
    "id": "REH0025",
    "debtorId": "NPL0145",
    "debtorName": "㈜케이앤피",
    "brand": "B",
    "court": "수원회생법원",
    "caseNumber": "2024개회229917",
    "type": "회생",
    "creditorNumber": "18-1",
    "planApproved": false,
    "dismissed": false,
    "debtAmount": 28508964,
    "approvedAmount": 2704342,
    "currentRound": "14회차",
    "monthlyPayment": 57997,
    "repaymentNote": "26.03.05 기준 변제계획인가 X",
    "overdueStatus": ""
  },
  {
    "id": "REH0026",
    "debtorId": "NPL0148",
    "debtorName": "이성민(개인회생)",
    "brand": "B",
    "court": "부산회생법원",
    "caseNumber": "2025개회116011",
    "type": "회생",
    "creditorNumber": "",
    "planApproved": false,
    "dismissed": false,
    "debtAmount": 0,
    "approvedAmount": 0,
    "currentRound": "",
    "monthlyPayment": 0,
    "repaymentNote": "진행 중",
    "overdueStatus": ""
  },
  {
    "id": "REH0027",
    "debtorId": null,
    "debtorName": "이덕원",
    "brand": "B",
    "court": "인천지법",
    "caseNumber": "2025개회1973",
    "type": "회생",
    "creditorNumber": "19",
    "planApproved": false,
    "dismissed": false,
    "debtAmount": 5165988,
    "approvedAmount": 959944,
    "currentRound": "29회차",
    "monthlyPayment": 15498,
    "repaymentNote": "",
    "overdueStatus": ""
  },
  {
    "id": "REH0028",
    "debtorId": "NPL0151",
    "debtorName": "김경화(이덕원 와이프)",
    "brand": "B",
    "court": "인천지법",
    "caseNumber": "2023개회5629",
    "type": "회생",
    "creditorNumber": "12",
    "planApproved": true,
    "dismissed": false,
    "debtAmount": 39805920,
    "approvedAmount": 9227889,
    "currentRound": "14회차",
    "monthlyPayment": 542209,
    "repaymentNote": "완료",
    "overdueStatus": ""
  },
  {
    "id": "REH0029",
    "debtorId": null,
    "debtorName": "연지훈",
    "brand": "B",
    "court": "서울회생법원",
    "caseNumber": "2025개회40869",
    "type": "회생",
    "creditorNumber": "16",
    "planApproved": false,
    "dismissed": false,
    "debtAmount": 10264543,
    "approvedAmount": 1176927,
    "currentRound": "28회차",
    "monthlyPayment": 17695,
    "repaymentNote": "",
    "overdueStatus": ""
  },
  {
    "id": "REH0030",
    "debtorId": "NPL0160",
    "debtorName": "박현정(마린씨) 회생",
    "brand": "B",
    "court": "",
    "caseNumber": "2025개회41868",
    "type": "회생",
    "creditorNumber": "14",
    "planApproved": true,
    "dismissed": false,
    "debtAmount": 6315356,
    "approvedAmount": 296892,
    "currentRound": "1~36회차",
    "monthlyPayment": 9768,
    "repaymentNote": "26.01.23 계좌누락 조치 完/5회차 금원 합산 입금(2/13)",
    "overdueStatus": ""
  },
  {
    "id": "REH0031",
    "debtorId": null,
    "debtorName": "황정화",
    "brand": "B",
    "court": "서울회생법원",
    "caseNumber": "2024개회1187902",
    "type": "회생",
    "creditorNumber": "7",
    "planApproved": true,
    "dismissed": false,
    "debtAmount": 42017156,
    "approvedAmount": 17876580,
    "currentRound": "1~60회차",
    "monthlyPayment": 303684,
    "repaymentNote": "",
    "overdueStatus": ""
  },
  {
    "id": "REH0032",
    "debtorId": null,
    "debtorName": "박진선",
    "brand": "B",
    "court": "",
    "caseNumber": "",
    "type": "회생",
    "creditorNumber": "",
    "planApproved": false,
    "dismissed": false,
    "debtAmount": 0,
    "approvedAmount": 0,
    "currentRound": "",
    "monthlyPayment": 0,
    "repaymentNote": "",
    "overdueStatus": ""
  },
  {
    "id": "REH0033",
    "debtorId": null,
    "debtorName": "이규재",
    "brand": "B",
    "court": "수원회생법원",
    "caseNumber": "2025하단/하면13781",
    "type": "파산/면책",
    "creditorNumber": "",
    "planApproved": false,
    "dismissed": false,
    "debtAmount": 0,
    "approvedAmount": 0,
    "currentRound": "",
    "monthlyPayment": 0,
    "repaymentNote": "채권조사기일 26.05.12",
    "overdueStatus": ""
  },
  {
    "id": "REH0034",
    "debtorId": null,
    "debtorName": "김재민",
    "brand": "B",
    "court": "대전지법",
    "caseNumber": "2023하단11210",
    "type": "파산/면책",
    "creditorNumber": "",
    "planApproved": false,
    "dismissed": false,
    "debtAmount": 0,
    "approvedAmount": 0,
    "currentRound": "",
    "monthlyPayment": 0,
    "repaymentNote": "",
    "overdueStatus": ""
  },
  {
    "id": "REH0035",
    "debtorId": "NPL0222",
    "debtorName": "조성규",
    "brand": "B",
    "court": "수원회생법원",
    "caseNumber": "2025개회132204",
    "type": "회생",
    "creditorNumber": "",
    "planApproved": false,
    "dismissed": false,
    "debtAmount": 0,
    "approvedAmount": 0,
    "currentRound": "",
    "monthlyPayment": 0,
    "repaymentNote": "진행 중",
    "overdueStatus": ""
  },
  {
    "id": "REH0036",
    "debtorId": "NPL0238",
    "debtorName": "이민우4",
    "brand": "B",
    "court": "서울회생법원",
    "caseNumber": "2023개회1175421",
    "type": "회생",
    "creditorNumber": "3",
    "planApproved": true,
    "dismissed": false,
    "debtAmount": 3405305,
    "approvedAmount": 646128,
    "currentRound": "1~36회차",
    "monthlyPayment": 17948,
    "repaymentNote": "260226 26회차 미납 1.99회 / 250818 18회분 전부 입금/ 1회분 더 입금되어야 함(17,948)",
    "overdueStatus": "미납"
  },
  {
    "id": "REH0037",
    "debtorId": "NPL0282",
    "debtorName": "김성훈",
    "brand": "M",
    "court": "수원회생법원",
    "caseNumber": "2024개회169978",
    "type": "회생",
    "creditorNumber": "11",
    "planApproved": true,
    "dismissed": false,
    "debtAmount": 6695687,
    "approvedAmount": 5248226,
    "currentRound": "13회차",
    "monthlyPayment": 208559,
    "repaymentNote": "완료",
    "overdueStatus": ""
  },
  {
    "id": "REH0038",
    "debtorId": null,
    "debtorName": "박정선",
    "brand": "M",
    "court": "",
    "caseNumber": "",
    "type": "파산/면책",
    "creditorNumber": "",
    "planApproved": false,
    "dismissed": false,
    "debtAmount": 0,
    "approvedAmount": 0,
    "currentRound": "",
    "monthlyPayment": 0,
    "repaymentNote": "20.06.26 결정",
    "overdueStatus": ""
  },
  {
    "id": "REH0039",
    "debtorId": "NPL0285",
    "debtorName": "윤보희",
    "brand": "M",
    "court": "서울회생법원",
    "caseNumber": "2025개회37104",
    "type": "회생",
    "creditorNumber": "10",
    "planApproved": false,
    "dismissed": false,
    "debtAmount": 21488304,
    "approvedAmount": 7151335,
    "currentRound": "5회차",
    "monthlyPayment": 193316,
    "repaymentNote": "채권자목록및변제계획안 수정허가 신청서 제출",
    "overdueStatus": ""
  },
  {
    "id": "REH0040",
    "debtorId": "NPL0307",
    "debtorName": "진효만",
    "brand": "M",
    "court": "서울회생법원",
    "caseNumber": "2025개회34309",
    "type": "회생",
    "creditorNumber": "24",
    "planApproved": true,
    "dismissed": false,
    "debtAmount": 27857523,
    "approvedAmount": 1168741,
    "currentRound": "45회차",
    "monthlyPayment": 107125,
    "repaymentNote": "",
    "overdueStatus": ""
  },
  {
    "id": "REH0041",
    "debtorId": "NPL0326",
    "debtorName": "이찬영",
    "brand": "M",
    "court": "광주지방법원",
    "caseNumber": "2022개회 527562(조회불가)",
    "type": "회생",
    "creditorNumber": "",
    "planApproved": false,
    "dismissed": false,
    "debtAmount": 0,
    "approvedAmount": 0,
    "currentRound": "",
    "monthlyPayment": 0,
    "repaymentNote": "",
    "overdueStatus": ""
  },
  {
    "id": "REH0042",
    "debtorId": "NPL0337",
    "debtorName": "김영현",
    "brand": "M",
    "court": "대구지법",
    "caseNumber": "2024개회284892",
    "type": "회생",
    "creditorNumber": "17",
    "planApproved": true,
    "dismissed": false,
    "debtAmount": 1544383,
    "approvedAmount": 345840,
    "currentRound": "27회차",
    "monthlyPayment": 9206,
    "repaymentNote": "",
    "overdueStatus": ""
  },
  {
    "id": "REH0043",
    "debtorId": null,
    "debtorName": "김순주",
    "brand": "M",
    "court": "부산회생법원",
    "caseNumber": "2025개회118372",
    "type": "회생",
    "creditorNumber": "",
    "planApproved": false,
    "dismissed": false,
    "debtAmount": 143610674,
    "approvedAmount": 105480000,
    "currentRound": "36회차",
    "monthlyPayment": 2930000,
    "repaymentNote": "26.01.02 회생위원 승계",
    "overdueStatus": ""
  },
  {
    "id": "REH0044",
    "debtorId": null,
    "debtorName": "오병진",
    "brand": "M",
    "court": "광주지방법원",
    "caseNumber": "2024개회516726",
    "type": "회생",
    "creditorNumber": "18",
    "planApproved": false,
    "dismissed": false,
    "debtAmount": 32730093,
    "approvedAmount": 2738101,
    "currentRound": "19회차",
    "monthlyPayment": 117058,
    "repaymentNote": "문차민 잘 변제 중 / 초과할 경우 부당이득으로 / 반환해야 하며 / 이에 대한 추이를 지켜봐야 함 /  / 채권자집회기일: 26.01.26",
    "overdueStatus": ""
  },
  {
    "id": "REH0045",
    "debtorId": "NPL0168",
    "debtorName": "조영은",
    "brand": "B",
    "court": "수원회생법원",
    "caseNumber": "2024개회290469",
    "type": "회생",
    "creditorNumber": "13-1",
    "planApproved": true,
    "dismissed": false,
    "debtAmount": 17078403,
    "approvedAmount": 6794193,
    "currentRound": "9회차",
    "monthlyPayment": 107277,
    "repaymentNote": "변제 중 / 연대채무자가 월 100만원씩 입금 중(회생과는 별도)",
    "overdueStatus": ""
  },
  {
    "id": "REH0046",
    "debtorId": "NPL0414",
    "debtorName": "김영준00",
    "brand": "B",
    "court": "울산지법",
    "caseNumber": "2023개회12344",
    "type": "회생",
    "creditorNumber": "11",
    "planApproved": false,
    "dismissed": false,
    "debtAmount": 28000000,
    "approvedAmount": 4157568,
    "currentRound": "1~36회차",
    "monthlyPayment": 115488,
    "repaymentNote": "",
    "overdueStatus": ""
  },
  {
    "id": "REH0047",
    "debtorId": "NPL0424",
    "debtorName": "이문주",
    "brand": "B",
    "court": "서울회생법원",
    "caseNumber": "2023개회1026666",
    "type": "회생",
    "creditorNumber": "3",
    "planApproved": false,
    "dismissed": false,
    "debtAmount": 10586241,
    "approvedAmount": 2557553,
    "currentRound": "7회차",
    "monthlyPayment": 71877,
    "repaymentNote": "",
    "overdueStatus": ""
  },
  {
    "id": "REH0048",
    "debtorId": null,
    "debtorName": "김보경",
    "brand": "B",
    "court": "서울회생법원",
    "caseNumber": "2023개회1106135",
    "type": "회생",
    "creditorNumber": "10",
    "planApproved": false,
    "dismissed": false,
    "debtAmount": 50049356,
    "approvedAmount": 4715144,
    "currentRound": "1~36회차",
    "monthlyPayment": 131004,
    "repaymentNote": "260226 기준 29회차",
    "overdueStatus": ""
  },
  {
    "id": "REH0049",
    "debtorId": "NPL0417",
    "debtorName": "신민정",
    "brand": "B",
    "court": "수원회생법원",
    "caseNumber": "2023개회147384",
    "type": "회생",
    "creditorNumber": "7",
    "planApproved": true,
    "dismissed": false,
    "debtAmount": 1995490,
    "approvedAmount": 413208,
    "currentRound": "1~36회차",
    "monthlyPayment": 11315,
    "repaymentNote": "260127 기준 27회차　／2026.10.25 변제종료",
    "overdueStatus": ""
  },
  {
    "id": "REH0050",
    "debtorId": "NPL0425",
    "debtorName": "채병민",
    "brand": "B",
    "court": "춘천지방법원",
    "caseNumber": "2025개회7904",
    "type": "회생",
    "creditorNumber": "10",
    "planApproved": true,
    "dismissed": false,
    "debtAmount": 32242848,
    "approvedAmount": 7567833,
    "currentRound": "3회차",
    "monthlyPayment": 39097,
    "repaymentNote": "260226 기준 변제 6회차/ 미납 0.05회 / 채권번호 10, 11  / 260226 기준 금원이 딜레이 되고 있으므로 미납여부 확인 및 입금 확인 必",
    "overdueStatus": "미납"
  },
  {
    "id": "REH0051",
    "debtorId": null,
    "debtorName": "이은정",
    "brand": "M",
    "court": "부산회생법원",
    "caseNumber": "2026개회101524",
    "type": "회생",
    "creditorNumber": "",
    "planApproved": false,
    "dismissed": false,
    "debtAmount": 0,
    "approvedAmount": 0,
    "currentRound": "",
    "monthlyPayment": 0,
    "repaymentNote": "",
    "overdueStatus": ""
  },
  {
    "id": "REH0052",
    "debtorId": null,
    "debtorName": "고윤기",
    "brand": "B",
    "court": "수원회생법원",
    "caseNumber": "2025개회119192",
    "type": "회생",
    "creditorNumber": "8",
    "planApproved": true,
    "dismissed": false,
    "debtAmount": 10517864,
    "approvedAmount": 3962855,
    "currentRound": "6회차",
    "monthlyPayment": 100925,
    "repaymentNote": "26.02.10 기준 9회차",
    "overdueStatus": ""
  },
  {
    "id": "REH0053",
    "debtorId": "NPL0041",
    "debtorName": "유기준",
    "brand": "B",
    "court": "서울회생법원",
    "caseNumber": "2025하단11408",
    "type": "파산/면책",
    "creditorNumber": "9",
    "planApproved": false,
    "dismissed": false,
    "debtAmount": 0,
    "approvedAmount": 0,
    "currentRound": "",
    "monthlyPayment": 0,
    "repaymentNote": "26.05.22 채권자집회",
    "overdueStatus": ""
  },
  {
    "id": "REH0054",
    "debtorId": null,
    "debtorName": "전경호",
    "brand": "M",
    "court": "의정부지방법원",
    "caseNumber": "2024개회229645",
    "type": "회생",
    "creditorNumber": "",
    "planApproved": false,
    "dismissed": true,
    "debtAmount": 0,
    "approvedAmount": 0,
    "currentRound": "",
    "monthlyPayment": 0,
    "repaymentNote": "2025.05.16 폐지",
    "overdueStatus": ""
  },
  {
    "id": "REH0055",
    "debtorId": null,
    "debtorName": "시시키나 예카테리나",
    "brand": "M",
    "court": "의정부지방법원",
    "caseNumber": "2025개회209200",
    "type": "회생",
    "creditorNumber": "9",
    "planApproved": false,
    "dismissed": false,
    "debtAmount": 0,
    "approvedAmount": 0,
    "currentRound": "",
    "monthlyPayment": 0,
    "repaymentNote": "25.05.28 추심금지명령 받고 진척 없음",
    "overdueStatus": ""
  },
  {
    "id": "REH0056",
    "debtorId": null,
    "debtorName": "우제선",
    "brand": "B",
    "court": "수원회생법원",
    "caseNumber": "2024개회262266",
    "type": "회생",
    "creditorNumber": "32",
    "planApproved": false,
    "dismissed": true,
    "debtAmount": 0,
    "approvedAmount": 0,
    "currentRound": "",
    "monthlyPayment": 0,
    "repaymentNote": "25.06.13 기각",
    "overdueStatus": ""
  },
  {
    "id": "REH0057",
    "debtorId": "NPL0113",
    "debtorName": "노태형",
    "brand": "B",
    "court": "부산회생법원",
    "caseNumber": "2024개회161943",
    "type": "회생",
    "creditorNumber": "7-1",
    "planApproved": false,
    "dismissed": true,
    "debtAmount": 0,
    "approvedAmount": 0,
    "currentRound": "",
    "monthlyPayment": 0,
    "repaymentNote": "2025.06.19 폐지",
    "overdueStatus": ""
  },
  {
    "id": "REH0058",
    "debtorId": null,
    "debtorName": "우일남",
    "brand": "D",
    "court": "제주지방법원",
    "caseNumber": "2024개회108174",
    "type": "회생",
    "creditorNumber": "33",
    "planApproved": true,
    "dismissed": false,
    "debtAmount": 2476000,
    "approvedAmount": 285723,
    "currentRound": "20회차",
    "monthlyPayment": 1607,
    "repaymentNote": "26.04.08기준 20회차/ 5.99 미납",
    "overdueStatus": "미납"
  },
  {
    "id": "REH0059",
    "debtorId": "NPL0264",
    "debtorName": "여세동",
    "brand": "B",
    "court": "대구지방법원",
    "caseNumber": "2022개회201152",
    "type": "회생",
    "creditorNumber": "2",
    "planApproved": true,
    "dismissed": false,
    "debtAmount": 94244346,
    "approvedAmount": 1022864,
    "currentRound": "1~58 회차",
    "monthlyPayment": 372639,
    "repaymentNote": "26.03.06 48회차 / 미납 2회차",
    "overdueStatus": "미납"
  },
  {
    "id": "REH0060",
    "debtorId": "NPL0189",
    "debtorName": "이재왕",
    "brand": "B",
    "court": "서울회생법원",
    "caseNumber": "2026개회14445",
    "type": "회생",
    "creditorNumber": "",
    "planApproved": false,
    "dismissed": false,
    "debtAmount": 0,
    "approvedAmount": 0,
    "currentRound": "",
    "monthlyPayment": 0,
    "repaymentNote": "26.03.10 추심금지결정문 송달",
    "overdueStatus": ""
  },
  {
    "id": "REH0061",
    "debtorId": null,
    "debtorName": "주식회사 올스타포스",
    "brand": "B",
    "court": "서울회생법원",
    "caseNumber": "2026하합1062",
    "type": "파산/면책",
    "creditorNumber": "",
    "planApproved": false,
    "dismissed": false,
    "debtAmount": 0,
    "approvedAmount": 0,
    "currentRound": "",
    "monthlyPayment": 0,
    "repaymentNote": "26.04.17 채권자 집회",
    "overdueStatus": ""
  },
  {
    "id": "REH0062",
    "debtorId": "NPL0206",
    "debtorName": "이진원",
    "brand": "D",
    "court": "대구회생법원",
    "caseNumber": "2026개회14500",
    "type": "회생",
    "creditorNumber": "",
    "planApproved": false,
    "dismissed": false,
    "debtAmount": 0,
    "approvedAmount": 0,
    "currentRound": "",
    "monthlyPayment": 0,
    "repaymentNote": "",
    "overdueStatus": ""
  }
];
